In [31]:
import numpy as np
import matplotlib.pyplot as plt

Dado el siguiente sistema dinamico con $x(t)$ perteneciente a los reales, tiempo continuo y parametro b perteneciente a los reales.

$$
\frac{dx}{dt} = x^2 (x + b) + x
$$

Indique con un circulo la respuesta correcta (solo una) a cada una de las preguntas a continuacion (cada respuesta vale 5 puntos)

<hr>

#### 1) Cuantos puntos de equilibrio hay cuando b = 5?

a) Dos <br>
b) Uno <br>
c) Cuatro <br>
d) Tres <br>
e) Ninguna de las opciones.

$$
\frac{dx}{dt} = x^2 (x + b) + x = x^3 + bx^2 + x
$$

Para buscar los puntos de equilibrio, pleanteamos:

$$
\frac{dx}{dt} = 0
$$

$$
x^3 + bx^2 + x = 0
$$

Para b = 5

$$
x^3 + 5x^2 + x = 0
$$

Calculamos las raices, de dos formas:

In [20]:
p = np.poly1d([1, 5, 1, 0])
raices = np.roots(p)
raices

array([-4.79128785, -0.20871215,  0.        ])

https://www.wolframalpha.com/input?i=x+%5E+3+%2B+5+*+x%5E2+%2B+x+

Vemos que hay 3, por lo tanto hay tres puntos de equilibrio, la respuesta es la (d)

<hr>

#### 2) Cuantos puntos de equilibrio hay cuando b = - 2?

a) Tres <br>
b) Dos <br>
c) Uno <br>
d) Cuatro <br>
e) Ninguna de las opciones.

$$
x^3 - 2x^2 + x = 0
$$

In [24]:
p = np.poly1d([1, -2, 1, 0])
raices = np.roots(p)
raices

array([1., 1., 0.])

https://www.wolframalpha.com/input?i=x+%5E+3+-+2+*+x%5E2+%2B+x+

Vemos que hay 2 raices, por lo tanto hay dos puntos de equilibrio, la respuesta es la (b)

<hr>

#### 3) Cuantos puntos de equilibrio hay cuando b = 1?

a) Tres <br>
b) Dos <br>
c) Uno <br>
d) Cuatro <br>
e) Ninguna de las opciones

$$
x^3 + x^2 + x = 0
$$

In [25]:
p = np.poly1d([1, 1, 1, 0])
raices = np.roots(p)
raices

array([-0.5+0.8660254j, -0.5-0.8660254j,  0. +0.j       ])

https://www.wolframalpha.com/input?i=x%5E3+%2B+x%5E2+%2B+x+

Vemos que hay 3 raices, dos complejas y un real, como el sistema dinamico tiene variables reales, entonces el unico punto fijo es el 0. Porl o tanto la respuesta es la (c).

<hr>

#### 4) Haga un analisis de bifurcacion respecto del parametro b. Cuantos valores criticos hay?

a) Dos <br>
b) Uno <br>
c) Ninguno <br>
d) Ninguna de las opciones

Analisis de bifurcacion:

$$
f(x) = x^2 (x + b) + x
$$

$$
Re(\frac{df(x_{eq})}{dt}) = 0
$$

$$
f(x) = x^3 + x^2b + x
$$

$$
\frac{df(x)}{dx} = x^3 + x^2b + x
$$

$$
\frac{df(x)}{dx} = 3x^2 + 2xb + 1
$$

Primero busquemos los puntos de equilibrio:

https://www.wolframalpha.com/input?i=x%5E2+%28x+%2B+b%29+%2B+x

$$
x_1 = 0
$$

$$
x_2 = \frac{1}{2} (-\sqrt{b^2 - 4} - b)
$$

$$
x_3 = \frac{1}{2} (\sqrt{b^2 - 4} - b)
$$

Ahora estudiemos la estabilidad de esto puntos de equilibrio:

$$
J(x) = 
\begin{bmatrix}
\frac{df(x)}{dx}
\end{bmatrix}
$$

$$
J(x) = 
\begin{bmatrix}
3x^2 + 2bx + 1
\end{bmatrix}
$$

Autovalores

$$
3x^2 + 2bx + 1 - \lambda = 0
$$

$x_1 = 0$

$$
\lambda = 1
$$

No cambia su estabilidad dependiendo de b, siempre es es un punto de equilibrio inestable. Por lo tanto para este punto fijo, no hay puntos criticos.

$x_2 = \frac{1}{2} (-\sqrt{b^2 - 4} - b)$

https://www.wolframalpha.com/input?i=3x+%5E+2+%2B+2bx+%2B+1++-+lambda+%3D+0+with+x+%3D+-1%2F2+*+%28%28b%5E2+-+4%29%5E%281%2F2%29+%2B+b%29

Soluciones $b = 0$ y $b = 2$

$x_2 = \frac{1}{2} (\sqrt{b^2 - 4} - b)$

https://www.wolframalpha.com/input?i=3x+%5E+2+%2B+2bx+%2B+1++-+lambda+%3D+0+with+x+%3D+1%2F2+*+%28%28b%5E2+-+4%29%5E%281%2F2%29+-+b%29

Soluciones $b = 0$ y $b = 2$

Por lo tanto la respuesta final es que hay dos valores criticos.

<hr>

#### 5) Selecciones la respuesta incorrecta

a) Hay una bifurcacion cuando $b^2 = 4$<br>
b) En $b = 0$ hay una bifurcacion<br>
c) Hay menos de tres valores criticos de b<br>
d) El sistema no es caotico<br>

b) Es correcta porque lo vemos en el inciso anterior.

c) Es correcta porque hay dos, lo vimos en el inciso anterior.

a) $b^2 = 4$

Entonces:

$x = -\frac{1}{2}b$

https://www.wolframalpha.com/input?i=3x%5E2+%2B+2bx+%2B+1+-+lambda+%3D+0+with+x+%3D+1%2F2+b

Lambda es siempre positivo, por lo tanto no cambia en ningun momento de signo, por lo tanto no es un punto critico.

Asi que por descarte la opcion incorrecta es la (d), es decir la respuesta final es la (d).

<hr>

#### 6) Para b = 1
a) Existe un punto fijo estable<br>
b) Hay puntos fijos estables e inestables<br>
c) Se produce una bifurcacion<br>
d) Existe un punto fijo inestable<br>
f) Ninguna de las opciones.

c) No, las bifurcaciones son en 0 y en 2.

$$
\frac{dx}{dt} = x^2 (x + 1) + x
$$

$$
x^3 + x^2 + x = 0
$$

https://www.wolframalpha.com/input?i=x%5E3+%2B+x%5E2+%2B+x

La unica raiz es $x=0$, es decir este es el unico punto fijo, veamos si es estable o inestable.

$$
\lambda = 3x^2 + 2x + 1
$$

$$
\lambda = 1
$$

Es mayor a cero, por lo tanto es inestable.

La respuesta es la (d)

<hr>

#### 7) Para b = 2

a) Hay un punto fijo estable <br>
b) Hay 3 puntos fijos <br>
c) Hay solo un punto fijo <br>
d) Hay un punto fijo inestable y uno neutral <br>
e) Ninguna de las opciones

$$
\frac{dx}{dt} = x^2 (x + 2) + x
$$

https://www.wolframalpha.com/input?i=x%5E3+%2B+2x%5E2+%2B+x

Hay dos raices, $x=-1$ y $x=0$

$$
\lambda = 3x^2 + 4x + 1
$$

$x = 0$

$$
\lambda = 1
$$

Inestable

$x = -1$

$$
\lambda = 3 - 4 + 1 = 0
$$

Neutral

Por lo tanto la respuesta correcta es la (d)

<hr>

#### 8) Para b = 4, si la condicion inicial es $x(0) = -0.5$, entonces:

a) x(t) decrecera hasta estabilizarse en un valor negativo <br>
b) x(t) convergera a cero <br>
c) x(t) permanecera sin cambios <br>
d) El sistema mostrara un comportamiento caotico <br>
e) Ninguna de las opciones

$$
\frac{dx}{dt} = x^2 (x + 4) + x = x^3 + 4x^2 + x
$$

https://www.wolframalpha.com/input?i=x+%5E+2++*+%28x+%2B+4%29+%2B+x

Puntos de equilibrio:

$$
x_1 = -2 - \sqrt 3 = -3.73
$$

$$
x_2 = \sqrt 3 - 2 = -0.26
$$

$$
x_3 = 0
$$

Estabilidad de los puntos de equilibrio

$$
J(x) =
\begin{bmatrix}
\frac{df(x)}{dx}
\end{bmatrix}
$$

$$
J(x) =
\begin{bmatrix}
3x^2 + 8x + 1
\end{bmatrix}
$$

$$
\lambda = 3x^2 + 8x + 1
$$

$x_1 = -2 - \sqrt 3$

$$
\lambda = 50 + 28 \sqrt 3
$$

$$
\lambda > 0
$$

Por lo tanto es un punto inestable

$x_2 = \sqrt 3 - 2$

$$
\lambda = 6 - 4 \sqrt 3 < 0
$$

$$
\lambda < 0
$$

Por lo tanto es un punto estable

$x_3 = 0$ 

$$
\lambda = 1
$$

$$
\lambda > 0
$$

Por lo tanto es un punto inestable