In [19]:
import numpy as np

Dado el siguiente sistema dinamico con $x(t)$ perteneciente a los reales, tiempo continuo y parametro b perteneciente a los reales.

$$
\frac{dx}{dt} = x^2 (x + b) + x
$$

Indique con un circulo la respuesta correcta (solo una) a cada una de las preguntas a continuacion (cada respuesta vale 5 puntos)

<hr>

#### 1) Cuantos puntos de equilibrio hay cuando b = 5?

a) Dos <br>
b) Uno <br>
c) Cuatro <br>
d) Tres <br>
e) Ninguna de las opciones.

$$
\frac{dx}{dt} = x^2 (x + b) + x = x^3 + bx^2 + x
$$

Para buscar los puntos de equilibrio, pleanteamos:

$$
\frac{dx}{dt} = 0
$$

$$
x^3 + bx^2 + x = 0
$$

Para b = 5

$$
x^3 + 5x^2 + x = 0
$$

Calculamos las raices, de dos formas:

In [20]:
p = np.poly1d([1, 5, 1, 0])
raices = np.roots(p)
raices

array([-4.79128785, -0.20871215,  0.        ])

https://www.wolframalpha.com/input?i=x+%5E+3+%2B+5+*+x%5E2+%2B+x+

Vemos que hay 3, por lo tanto hay tres puntos de equilibrio, la respuesta es la (d)

<hr>

#### 2) Cuantos puntos de equilibrio hay cuando b = - 2?

a) Tres <br>
b) Dos <br>
c) Uno <br>
d) Cuatro <br>
e) Ninguna de las opciones.

$$
x^3 - 2x^2 + x = 0
$$

In [24]:
p = np.poly1d([1, -2, 1, 0])
raices = np.roots(p)
raices

array([1., 1., 0.])

https://www.wolframalpha.com/input?i=x+%5E+3+-+2+*+x%5E2+%2B+x+

Vemos que hay 2 raices, por lo tanto hay dos puntos de equilibrio, la respuesta es la (b)

<hr>

#### 3) Cuantos puntos de equilibrio hay cuando b = 1?

$$
x^3 + x^2 + x = 0
$$

In [25]:
p = np.poly1d([1, 1, 1, 0])
raices = np.roots(p)
raices

array([-0.5+0.8660254j, -0.5-0.8660254j,  0. +0.j       ])

https://www.wolframalpha.com/input?i=x%5E3+%2B+x%5E2+%2B+x+