In [19]:
import numpy as np

Dado el siguiente sistema dinamico con $x(t)$ perteneciente a los reales, tiempo continuo y parametro b perteneciente a los reales.

$$
\frac{dx}{dt} = x^2 (x + b) + x
$$

Indique con un circulo la respuesta correcta (solo una) a cada una de las preguntas a continuacion (cada respuesta vale 5 puntos)

<hr>

#### 1) Cuantos puntos de equilibrio hay cuando b = 5?

a) Dos <br>
b) Uno <br>
c) Cuatro <br>
d) Tres <br>
e) Ninguna de las opciones.

$$
\frac{dx}{dt} = x^2 (x + b) + x = x^3 + bx^2 + x
$$

Para buscar los puntos de equilibrio, pleanteamos:

$$
\frac{dx}{dt} = 0
$$

$$
x^3 + bx^2 + x = 0
$$

Para b = 5

$$
x^3 + 5x^2 + x = 0
$$

Calculamos las raices, de dos formas:

In [20]:
p = np.poly1d([1, 5, 1, 0])
raices = np.roots(p)
raices

array([-4.79128785, -0.20871215,  0.        ])

https://www.wolframalpha.com/input?i=x+%5E+3+%2B+5+*+x%5E2+%2B+x+

Vemos que hay 3, por lo tanto hay tres puntos de equilibrio, la respuesta es la (d)

<hr>

#### 2) Cuantos puntos de equilibrio hay cuando b = - 2?

a) Tres <br>
b) Dos <br>
c) Uno <br>
d) Cuatro <br>
e) Ninguna de las opciones.

$$
x^3 - 2x^2 + x = 0
$$

In [24]:
p = np.poly1d([1, -2, 1, 0])
raices = np.roots(p)
raices

array([1., 1., 0.])

https://www.wolframalpha.com/input?i=x+%5E+3+-+2+*+x%5E2+%2B+x+

Vemos que hay 2 raices, por lo tanto hay dos puntos de equilibrio, la respuesta es la (b)

<hr>

#### 3) Cuantos puntos de equilibrio hay cuando b = 1?

a) Tres <br>
b) Dos <br>
c) Uno <br>
d) Cuatro <br>
e) Ninguna de las opciones

$$
x^3 + x^2 + x = 0
$$

In [25]:
p = np.poly1d([1, 1, 1, 0])
raices = np.roots(p)
raices

array([-0.5+0.8660254j, -0.5-0.8660254j,  0. +0.j       ])

https://www.wolframalpha.com/input?i=x%5E3+%2B+x%5E2+%2B+x+

Vemos que hay 3 raices, dos complejas y un real, como el sistema dinamico tiene variables reales, entonces el unico punto fijo es el 0. Porl o tanto la respuesta es la (c).

<hr>

#### 4) Haga un analisis de bifurcacion respecto del parametro b. Cuantos valores criticos hay?

a) Dos <br>
b) Uno <br>
c) Ninguno <br>
d) Ninguna de las opciones

Analisis de bifurcacion:

$$
f(x) = x^2 (x + b) + x
$$

$$
Re(\frac{df(x_{eq})}{dt}) = 0
$$

$$
f(x) = x^3 + x^2b + x
$$

$$
\frac{df(x)}{dx} = x^3 + x^2b + x
$$

$$
\frac{df(x)}{dx} = 3x^2 + 2xb + 1
$$

Primero busquemos los puntos de equilibrio:

https://www.wolframalpha.com/input?i=x%5E2+%28x+%2B+b%29+%2B+x

$$
x_1 = 0
$$

$$
x_2 = \frac{1}{2} (-\sqrt{b^2 - 4} - b)
$$

$$
x_3 = \frac{1}{2} (\sqrt{b^2 - 4} - b)
$$

Ahora estudiemos la estabilidad de esto puntos de equilibrio:

$$
J(x) = 
\begin{bmatrix}
\frac{df(x)}{dx}
\end{bmatrix}
$$

$$
J(x) = 
\begin{bmatrix}
3x^2 + 2bx + 1
\end{bmatrix}
$$

Autovalores

$$
3x^2 + 2bx + 1 - \lambda = 0
$$

$x_1 = 0$

$$
\lambda = 1
$$

No cambia su estabilidad dependiendo de b, siempre es es un punto de equilibrio inestable. Por lo tanto para este punto fijo, no hay puntos criticos.

$x_2 = \frac{1}{2} (-\sqrt{b^2 - 4} - b)$

https://www.wolframalpha.com/input?i=3x+%5E+2+%2B+2bx+%2B+1++-+lambda+%3D+0+with+x+%3D+-1%2F2+*+%28%28b%5E2+-+4%29%5E%281%2F2%29+%2B+b%29

Soluciones $b = 0$ y $b = 2$

$x_2 = \frac{1}{2} (\sqrt{b^2 - 4} - b)$

https://www.wolframalpha.com/input?i=3x+%5E+2+%2B+2bx+%2B+1++-+lambda+%3D+0+with+x+%3D+1%2F2+*+%28%28b%5E2+-+4%29%5E%281%2F2%29+-+b%29

Soluciones $b = 0$ y $b = 2$

Por lo tanto la respuesta final es que hay dos valores criticos.